---- TASK 2: CRUD OPERATIONS

-- 1. Insert a new product with the following details: Product Name: "Laptop", Price: 1000.00, Stock Quantity: 50.
INSERT INTO
    product (product_name, price, stock_quantity)
VALUES
    ('Laptop', 1000.00, 50);

--- 2. Update the stock quantity of the product with product_id = 3 to 75.
UPDATE
    product
SET
    stock_quantity = 75
WHERE
    product_id = 3;

---- 3.Delete the order with order_id = 10 and its associated order items
DELETE FROM
    order_item
WHERE
    order_id = 10;

DELETE FROM
    orders
WHERE
    order_id = 10;

---- 4. Retrieve the customer 's first and last names who placed the order with order_id = 5
SELECT
    customer.first_name,
    customer.last_name
FROM
    customer
    INNER JOIN orders ON customer.customer_id = orders.customer_id
WHERE
    orders.order_id = 5;

---- 5.Calculate the total revenue generated by each product (sum of subtotals from order items)

SELECT
    product.product_name,
    SUM(order_item.subtotal) AS total_revenue
FROM
    product
    INNER JOIN order_item ON product.product_id = order_item.product_id
GROUP BY
    product.product_name;
