---- TASK 3: STORED PROCEDURES
----Create a stored procedure that calculates and returns the total revenue generated by a specific customer.
CREATE OR REPLACE FUNCTION calculate_customer_revenue(customer_id_sent INT) 
RETURNS NUMERIC AS $$
DECLARE 
    total_revenue NUMERIC;

BEGIN
    SELECT COALESCE(SUM(oi.subtotal), 0) INTO total_revenue
    FROM customer c
    LEFT JOIN orders o ON c.customer_id = o.customer_id
    LEFT JOIN order_item oi ON o.order_id = oi.order_id
    WHERE c.customer_id = customer_id_sent;

    RETURN total_revenue;
END;
$$ LANGUAGE plpgsql;

-- Ejemplo de llamada a la función y asignación del resultado a una columna "total_revenue"
SELECT calculate_customer_revenue(2) AS total_revenue;
